name = "CharFuncPricing"
uuid = "1fb851c3-be98-478b-9657-166436d5cfc1"
authors = ["Jherek Healy <jherekhealy@protonmail.com>"]
version = "0.1.2"

[deps]

[extras]
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TaylorSeries = "6aa5eb33-94cf-58f4-a9d0-e4b2c4fc25ea"

[targets]
test = ["Test", "Nemo","TaylorSeries"]
